## The functions makeCacheMatrix and cacheSolve compute the inverse of an invertible matrix and store the
## result in the cache.

## The function makeCacheMatrix takes an invertible matrix as argument and returns a special matrix object.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL  
  }                         
  
  get <- function() x
  setinverse <- function(inverse) inv <<- inverse
  getinverse <- function() inv
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
  
}


## The function cacheSolve computes the inverse of the special matrix object generated by makeCacheMatrix.
## It then stores the result in the cache. If the matrix object is changed by makeCacheMatrix, solveCache 
## will recompute the inverse. If not, it will print out the cached result.

cacheSolve <- function(x, ...) {
  inv <- x$getinverse()
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  }
  data <- x$get()
  inv <- solve(data, ...)
  x$setinverse(inv)
  inv                                    
}


## EXAMPLE:
## >my_special_matrix_object <- makeCacheMatrix(matrix(c(1:4), ncol = 2, nrow = 2))
## > cacheSolve(my_special_matrix_object)
## [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5
## > cacheSolve(my_special_matrix_object)
## getting cached data
## [,1] [,2]
## [1,]   -2  1.5
## [2,]    1 -0.5
## > 
